ANDROID: GKI: x86_64: Update Symbol-list and ABI
After enabling pkvm we were missing these two symbols in the ABI. Let's
add them.
It fixes the following errors:
ERROR: modpost: "physical_mask" [drivers/gpu/drm/i915/i915.ko] undefined!
ERROR: modpost: "cc_mkdec" [drivers/gpu/drm/i915/i915.ko] undefined!
ERROR: modpost: "cc_mkdec" [drivers/platform/x86/intel/pmt/pmt_class.ko] undefined!

ABI report:
1 function symbol(s) added
  'u64 cc_mkdec(u64)'

1 variable symbol(s) added
  'phys_addr_t physical_mask'

Test: tools/bazel run //private/devices/google/x86-64/intel/brya:brya_dist --config=brya
Bug: 444310763
Upstream-Task: 402758258

Change-Id: I21044f110b3786b32d409a037be87f8e8bdac084
Signed-off-by: Ricardo Ribalda <ribalda@google.com>